### ISSUE TITLE
Example code not working

### ISSUE THREAD

**Issue by YeapGuy** [Matrixchung/SFM-V1.7#3]
Hi!
First of all, thank you for this library. It's the only way I found to interact with this fingerprint sensor I got from Aliexpress. I thought that it was internally the same as the widely supported "R503 Grow Fingerprint Reader", but alas, it apparently isn't even compatible.

Unfortunately, when I tried the example code you provided, I only get a spam of this in the serial monitor:
```
 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 3424, room 16 
tail 0
chksum 0x2e
load 0x3fff20b8, len 40, room 8 
tail 0
chksum 0x2b
csum 0x2b
v00043db0
~ld
```
This apparently means the NodeMCU hard-crashed from what I gathered online.
Do you have any clue as to why this is happening? The example code seems to be working for others, judging by the other issues on this repo.
My NodeMCU works with my Arduino IDE just fine with some simple blink LED code, so I don't think it's a bad unit or wrong config of some sort.

**Comment by Matrixchung** [comment]
Hello YeapGuy,
You said that your mcu works well with simple blinking code, so let's assume that you have a working mcu. Could you tell me how your NodeMCU is powered? It seems that a low-capacity power caused MCU to restart repeatedly when connected an extra sensor. But in theory, the sensor is designed for low power use, so it shouldn't drain much energy.

To find the problem, you can:

-  Switch to another strong power supply (if you are using computer's USB port)
- Or disconnect the sensor with the example code still in the mcu
- Or leave the sensor connected, but burn a simple code without controlling the sensor.

Feel free to ask more!

**Comment by Matrixchung** [comment]
Plus, I found some information for ESP8266:

> rst cause : 2
External reset is triggered by the reset pin of the ESP8266. This is the reason you would see when the ESP8266 is reset explicitly via the pin or when the ESP8266 wakes up from deep sleep (because that involves a GPIO driving the reset pin).

So, you should also check the pin selection according to you mcu's datasheet and check if anything is different from your blinking example.

**Comment by YeapGuy** [comment]
Thanks for your reply!

It's not the power draw, I ruled that out already. It repeatedly crashes/resets even when the fingerprint sensor is completely disconnected.
I don't think it has to do with the reset pin, I don't use it at all. I checked the pinout, and the GPIO pins I used don't have any special functions of this sort. Maybe NodeMCU has some internal logic controlling the reset pin? That would've also affected other programs, like the simple LED blink, wouldn't it? To rule that out though, I could try this entire thing with another ESP8266 board I have at home - Wemos D1 Mini.
Now that I think about it, that should've been one of the first things to try... Well, I'll give it a shot when I find some time, and then update here.

**Comment by Matrixchung** [comment]
This driver was initially designed for both ESP32 and Arduino uses. Thus, I haven't done some tests on ESP8266 platform because I don't have a board with that chip. But in theory, if compiler has no `ESP32` defined, it will use the default settings as original Arduino.

**Comment by YeapGuy** [comment]
No luck with different boards. Same problem.
How can I help debug this issue? I have no clue what to do now...

**Comment by YeapGuy** [comment]
I solved the reset issue! But it's still not fully working. The code isn't crashing, but I can't register any finger, it always fails on step 1. A clue that might help is that the ring colors also behave a bit weird? It takes like 8 seconds for `SFM.setRingColor` to execute, and the color doesn't always change in real life. I don't think that's normal, is it?

**Comment by YeapGuy** [comment]
I figured it all out! Needed to change some things in the library. I might fork yours and commit my changes, in case anyone comes across a similar issue in the future

**Comment by Matrixchung** [comment]
> I figured it all out! Needed to change some things in the library. I might fork yours and commit my changes, in case anyone comes across a similar issue in the future

Dear YeapGuy,
Of course you can fork mine and do some changes, I'm happy to hear that you have solved your issues. Plus, please let me know if my codes have something that won't work and if possible, create a pull request. Thank you!

**Comment by YeapGuy** [comment]
Sure :) One more hardware thing came up which you might know the answer to: I'm planning to wire the green cable (VCC) to always-on 3.3V, along with the white V_TOUCH cable (which is always on 3.3V). The reason for this is that I don't have enough GPIO pins on the ESP I'm going to be using this sensor with.
I thought it would work without issues in this configuration, albeit with a higher power consumption (which I don't mind), but it doesn't work at all. Do you possibly know why?

**Comment by Matrixchung** [comment]
Have you ever tested that connecting the VCC and V_TOUCH to external power source (and make sure it has the same GND with your MCU)? In theory, your configuration should definitely work. Could you tell me where's the problem, like the sensor doesn't boot up or shows no reaction to fingertouch, etc.?

**Comment by YeapGuy** [comment]
The sensor didn't react at all. As if VCC was not connected...

Anyways, I figured it out.
I did some measuring, and it turned out, that due to the power draw of VCC of the SFM-V1.7, the voltage on the GPIO pin that's powering it drops way below 3.3V, to like 2.4-2.6V.
I didn't expect that this could be the issue. 3.3V being too **much** for the module... The datasheets all say input should be 3.3V +- 5%...
But well, I gave it a shot, because I didn't know what else could possibly cause this strange behavior...
I connected VCC to 3.3V via a 30 ohm resistor, which according to my measurements should drop the voltage to a similar level as when VCC is connected to a GPIO pin. Here, let me make a diagram to be clear:
```
+-------------+          +------------+
|  MCU (ESP)  |          |  SFM-V1.7  |
+-------------+          +------------+
|        3.3V |__________| V_TOUCH    |
|             | \__(30Ω)_| VCC        |
|         GND |__________| GND        |
|   GPIO (TX) |__________| TX         |
|   GPIO (RX) |__________| RX         |
|  GPIO (IRQ) |__________| TOUCH_OUT  |
+-------------+          +------------+
```
Now everything seems to work! What a strange fix though....

**Comment by Matrixchung** [comment]
As you said, this was a pretty strange fix.
I have no idea about why the VCC should be powered with a lower voltage. In my tests, the GPIO pin cannot handle such a power draw, causing the module stop functioning. 
But now that you have fixed it through your way, congratulations!
