### ISSUE TITLE
setPassword / verifyPassword

### ISSUE THREAD

**Issue by lhofinger** [Matrixchung/SFM-V1.7#8]
Hello,
Unfortunately, I can't read the documentation in Chinese... Does this sensor support setting a password? If so, I would be great if you could implement it ;-)
Laurent

**Comment by Matrixchung** [comment]
What password do you mean? The sensor itself doesn't need a password, and if you want to use bluetooth or other password to unlock your things, maybe you can edit it in your main code.

**Comment by lhofinger** [comment]
Hello.

 

I’ve seen that on

 

https://www.circuitstate.com/libraries/r307-optical-fingerprint-scanner-library-for-arduino-documentation/#setpassword

or

https://adafruit.github.io/Adafruit-Fingerprint-Sensor-Library/html/class_adafruit___fingerprint.html#a71d38fce7ab2eacb63d222e71cac65af

 

setPassword() : Set the password on the sensor (future communication will require password verification so don't forget it!!!)

verifyPassword (void) : Verifies the sensors' access password (default password is 0x0000000).

 

I think it is to avoid connecting other sensors with foreign fingerprints and take action…

 

Laurent

 

 

 

De : Matr1x. ***@***.***> 
Envoyé : mardi 30 mai 2023 04:46
À : Matrixchung/SFM-V1.7 ***@***.***>
Cc : Paludour ***@***.***>; Author ***@***.***>
Objet : Re: [Matrixchung/SFM-V1.7] setPassword / verifyPassword (Issue #8)

 

What password do you mean? The sensor itself doesn't need a password, and if you want to use bluetooth or other password to unlock your things, maybe you can edit it in your main code.

**Comment by Matrixchung** [comment]
Another solution to this problem may be checking the module's uuid with SFM_Module::getUuid() and store it to prevent foreign sensor.

**Comment by lhofinger** [comment]
You are right… but somebody could also overwrite fingerprints with their own in the sensor.

 

 

De : Matr1x. ***@***.***> 
Envoyé : mardi 30 mai 2023 07:54
À : Matrixchung/SFM-V1.7 ***@***.***>
Cc : Paludour ***@***.***>; Author ***@***.***>
Objet : Re: [Matrixchung/SFM-V1.7] setPassword / verifyPassword (Issue #8)

 

Another solution to this problem may be checking the module's uuid with SFM_Module::getUuid() and store it to prevent foreign sensor.

**Comment by Matrixchung** [comment]
Unfortunately, I have no idea about that. Maybe you can prevent others from interacting the sensor physically.
